# Each new term in the Fibonacci sequence is generated by adding the previous two terms. 
# By starting with 1 and 2, the first 10 terms will be: 1, 2, 3, 5, 8, 13, 21, 34, 55, 89...

# By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.


def even_fibonacci_sum(limit)
  fib_nums = [1, 2]
  next_num = 0

  while next_num < limit
    next_num = (fib_nums[-1] + fib_nums[-2])
    fib_nums << next_num
  end

  fib_nums.select { |n| n % 2 == 0 }.inject(:+)
end

even_fibonacci_sum(4000000)